# 第一章 开始数据挖掘之旅
* 数据挖掘旨在让计算机根据已有数据做出决策
* 数据挖掘步骤:创建数据集 调整算法

In [1]:
print("Hello, world!")

Hello, world!


In [10]:
# 亲和性分析实例
# 亲和性分析:根据样本个体(物体)间的相似度,确定关系远近
# 商品推荐
import numpy as np
import sys, os
dataset_filename = "/home/fern/Downloads/Python数据挖掘入门与实践文件/Code/Chapter 1/affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

# 查看前5次交易中顾客买了什么
print(X[:5]) # 1表示购买,0表示没购买

# 找出规则,挑选规则的方法常用的是支持度(support)和置信度(confidence)
# 支持度指数据集中规则应验次数
# 置信度是规则准确率

# 求解规则的支持度和置信度
# First, how many rows contain our premise: that a person is buying apples
num_apple_purchases = 0
for sample in X:
    if sample[3] == 1: # This person bought Apples
        num_apple_purchases += 1
print("{0} people bought Apple".format(num_apple_purchases)) # 36



[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]
36 people bought Apple


In [12]:
# 创建字典存放计算结果
# defaultdict:查找的键不存在返回一个默认值
# 统计规则应验\规则无效及条件相同的规则数量
from collections import defaultdict
# Now compute for all possible rules
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise in range(n_features):
        if sample[premise] == 0: continue
        # Record that the premise was bought in another transaction
        num_occurences[premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion:  # It makes little sense to measure if X -> X.
                continue
            if sample[conclusion] == 1:
                # This person also bought the conclusion item
                valid_rules[(premise, conclusion)] += 1
            else:
                # This person bought the premise, but not the conclusion
                invalid_rules[(premise, conclusion)] += 1
support = valid_rules  # 支持度
confidence = defaultdict(float) # 置信度
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / num_occurences[premise]

d_rules[rule] / num_occurances[premise]

NameError: name 'n_features' is not defined